In [1]:
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv("disease_prediction.csv")
df

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo

In [7]:
X = df.drop(columns=['prognosis'])

In [11]:
y = df["prognosis"]

In [12]:
X.shape

(4920, 132)

In [28]:
y.shape

(4920,)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [30]:
X_train.shape

(3936, 132)

In [31]:
X_test.shape

(984, 132)

In [32]:
y_train.shape

(3936,)

In [33]:
y_test.shape

(984,)

In [34]:
X_train.describe()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
count,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,...,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000
mean,0.142785,0.162093,0.023120,0.044970,0.022358,0.162602,0.137703,0.044461,0.043699,0.021596,...,0.021596,0.021850,0.021596,0.023628,0.023882,0.023374,0.023628,0.023120,0.022866,0.023120
std,0.349897,0.368583,0.150303,0.207264,0.147863,0.369049,0.344632,0.206144,0.204451,0.145377,...,0.145377,0.146211,0.145377,0.151907,0.152701,0.151107,0.151907,0.150303,0.149495,0.150303
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [35]:
X_test.describe()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
count,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,...,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000
mean,0.117886,0.150407,0.017276,0.045732,0.020325,0.160569,0.144309,0.047764,0.050813,0.023374,...,0.023374,0.022358,0.023374,0.021341,0.020325,0.022358,0.021341,0.023374,0.024390,0.023374
std,0.322637,0.357651,0.130366,0.209009,0.141182,0.367320,0.351581,0.213375,0.219727,0.151165,...,0.151165,0.147919,0.151165,0.144593,0.141182,0.147919,0.144593,0.151165,0.154336,0.151165
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
dtc = DecisionTreeClassifier()

In [38]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [39]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [40]:
y_pred = dtc.predict(X_test)

In [46]:
from sklearn.metrics import confusion_matrix

In [47]:
print(confusion_matrix(y_test, y_pred))

[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]

In [48]:
from sklearn.metrics import classification_report

In [49]:
print(classification_report(y_test, y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic cholestasis       1.00      1.00      1.00        15
                            Common Cold       1.00      1.00      1.00        23
                                 Dengue       1.00      1.00      1.00        26
                              Diabetes        1.00      1.00      1.00        21
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        29
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        19
                                   GERD       1.00      1.00      1.00        28
                        Gastroenteritis       1.00      1.00      1.00        25
                           Heart attack       1.00      1.00      1.00        23
                            Hepatitis B       1.00      1.00      1.00        27
                            Hepatitis C       1.00      1.00      1.00        26
                            Hepatitis D       1.00      1.00      1.00        23
                            Hepatitis E       1.00      1.00      1.00        29
                          Hypertension        1.00      1.00      1.00        25
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        26
                         Hypothyroidism       1.00      1.00      1.00        21
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        19
                                Malaria       1.00      1.00      1.00        22
                               Migraine       1.00      1.00      1.00        25
                        Osteoarthristis       1.00      1.00      1.00        22
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        17
                              Pneumonia       1.00      1.00      1.00        28
                              Psoriasis       1.00      1.00      1.00        22
                           Tuberculosis       1.00      1.00      1.00        25
                                Typhoid       1.00      1.00      1.00        19
                Urinary tract infection       1.00      1.00      1.00        26
                         Varicose veins       1.00      1.00      1.00        22
                            hepatitis A       1.00      1.00      1.00        34

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

In [51]:
dtc.feature_importances_

array([0.02390956, 0.00099962, 0.0039713 , 0.        , 0.02240742,
       0.00400533, 0.        , 0.0012817 , 0.        , 0.02140323,
       0.00101257, 0.00097557, 0.        , 0.        , 0.00125005,
       0.        , 0.        , 0.        , 0.        , 0.02544739,
       0.        , 0.        , 0.        , 0.        , 0.00177008,
       0.0199796 , 0.        , 0.00274368, 0.01158942, 0.00127194,
       0.        , 0.00077114, 0.        , 0.02437235, 0.00102537,
       0.02444013, 0.02448408, 0.00062503, 0.02249272, 0.00441687,
       0.0220746 , 0.02385741, 0.        , 0.00136562, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02524988,
       0.        , 0.0012642 , 0.        , 0.        , 0.00074222,
       0.        , 0.        , 0.        , 0.02418642, 0.        ,
       0.00076353, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0257632 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00128489, 0.02187651,
       0.        , 0.        , 0.00247274, 0.02470543, 0.        ,
       0.        , 0.02544769, 0.00125304, 0.        , 0.        ,
       0.00127753, 0.02286783, 0.        , 0.02570441, 0.        ,
       0.02385855, 0.        , 0.02408555, 0.02347594, 0.02573853,
       0.02518883, 0.02499409, 0.02123597, 0.        , 0.        ,
       0.02576219, 0.01979795, 0.02059552, 0.02397807, 0.02315459,
       0.        , 0.02422996, 0.        , 0.        , 0.02370029,
       0.        , 0.        , 0.02356208, 0.02474116, 0.02468585,
       0.02448292, 0.        , 0.        , 0.02106046, 0.00249708,
       0.        , 0.02440438, 0.        , 0.        , 0.00246118,
       0.        , 0.02350556])

In [53]:
X.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'pus_filled_pimples', 'blackheads', 'scurring', 'skin_peeling',
       'silver_like_dusting', 'small_dents_in_nails', 'inflammatory_nails',
       'blister', 'red_sore_around_nose', 'yellow_crust_ooze'],
      dtype='object', length=132)

In [55]:
features = pd.DataFrame(dtc.feature_importances_, index = X.columns)

In [57]:
features.head(10)

                             0
itching               0.023910
skin_rash             0.001000
nodal_skin_eruptions  0.003971
continuous_sneezing   0.000000
shivering             0.022407
chills                0.004005
joint_pain            0.000000
stomach_pain          0.001282
acidity               0.000000
ulcers_on_tongue      0.021403

In [65]:
dtc2 = DecisionTreeClassifier(criterion = 'entropy', ccp_alpha=0.04)

In [66]:
dtc2.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.04, criterion='entropy')

In [67]:
y_pred2 = dtc2.predict(X_test)

In [70]:
print(confusion_matrix(y_test, y_pred2))

[[15  0  0 ...  0  0  0]
 [ 0 28  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ... 21  0  0]
 [ 0  0  0 ...  0 20  0]
 [ 0  0  0 ...  0  0 31]]

In [71]:
print(classification_report(y_test, y_pred2))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       0.79      0.83      0.81        18
                                   AIDS       0.74      0.93      0.82        30
                                   Acne       0.73      0.92      0.81        24
                    Alcoholic hepatitis       0.77      0.96      0.86        25
                                Allergy       1.00      0.83      0.91        24
                              Arthritis       1.00      0.70      0.82        23
                       Bronchial Asthma       0.00      0.00      0.00        33
                   Cervical spondylosis       0.79      1.00      0.88        23
                            Chicken pox       1.00      0.86      0.92        21
                    Chronic cholestasis       0.87      0.87      0.87        15
                            Common Cold       1.00      0.87      0.93        23
                                 Dengue       1.00      0.96      0.98        26
                              Diabetes        1.00      1.00      1.00        21
           Dimorphic hemmorhoids(piles)       1.00      0.90      0.95        29
                          Drug Reaction       0.00      0.00      0.00        24
                       Fungal infection       0.21      0.84      0.34        19
                                   GERD       0.00      0.00      0.00        28
                        Gastroenteritis       0.96      0.88      0.92        25
                           Heart attack       0.41      0.83      0.55        23
                            Hepatitis B       1.00      0.93      0.96        27
                            Hepatitis C       0.00      0.00      0.00        26
                            Hepatitis D       0.44      0.83      0.58        23
                            Hepatitis E       1.00      0.97      0.98        29
                          Hypertension        0.70      0.84      0.76        25
                        Hyperthyroidism       1.00      0.96      0.98        24
                           Hypoglycemia       1.00      0.92      0.96        26
                         Hypothyroidism       1.00      0.90      0.95        21
                               Impetigo       1.00      0.79      0.88        24
                               Jaundice       0.33      0.79      0.47        19
                                Malaria       0.95      0.95      0.95        22
                               Migraine       1.00      0.88      0.94        25
                        Osteoarthristis       0.84      0.95      0.89        22
           Paralysis (brain hemorrhage)       0.74      0.83      0.78        24
                    Peptic ulcer diseae       1.00      0.82      0.90        17
                              Pneumonia       1.00      0.93      0.96        28
                              Psoriasis       1.00      0.77      0.87        22
                           Tuberculosis       1.00      0.84      0.91        25
                                Typhoid       1.00      1.00      1.00        19
                Urinary tract infection       0.95      0.81      0.88        26
                         Varicose veins       0.67      0.91      0.77        22
                            hepatitis A       1.00      0.91      0.95        34

                               accuracy                           0.79       984
                              macro avg       0.78      0.80      0.77       984
                           weighted avg       0.77      0.79      0.77       984

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [72]:
feature2 = pd.DataFrame(dtc2.feature_importances_, index = X.columns)

In [73]:
feature2.head(10)

                             0
itching               0.019686
skin_rash             0.062203
nodal_skin_eruptions  0.000000
continuous_sneezing   0.000000
shivering             0.009515
chills                0.013931
joint_pain            0.013092
stomach_pain          0.000000
acidity               0.000000
ulcers_on_tongue      0.000000

In [74]:
from sklearn.metrics import accuracy_score

In [75]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [76]:
print("Accuracy:", accuracy_score(y_test, y_pred2))

Accuracy: 0.7865853658536586